_target_: models.timmclassifier.TimmClassifier

# Model parameters
model_name: "mobilenetv2_100"
num_classes: 2
pretrained: true

# Learning rate
lr: 1e-3

# Scheduler parameters
lr_scheduler_patience: 3
lr_scheduler_factor: 0.1
lr_scheduler_min_lr: 1e-6

# Optimizer parameters
optimizer_weight_decay: 1e-4
optimizer_beta1: 0.9
optimizer_beta2: 0.999
optimizer_eps: 1e-8
