mlflow:
  _target_: lightning.pytorch.loggers.MLFlowLogger
  experiment_name: ${experiment_name}
  tracking_uri: file:${paths.log_dir}/mlruns
  save_dir: ${paths.log_dir}/mlruns
  run_name: null
  log_model: False
  prefix: ""
  tags: 
    model_name: ${model.model_name}
    batch_size: ${data.batch_size} 