name: Train and Report

on:
  push:
    branches: [ dvc ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMPARE_BRANCH: dvc

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      env:
        UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
      run: |
        uv sync
        uv pip install pandas matplotlib seaborn

    - name: Setup DVC
      uses: iterative/setup-dvc@v1

    - name: Setup CML
      uses: iterative/setup-cml@v2

    - name: Pull DVC data
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: dvc pull

    - name: Train model
      run: |
        python src/train.py experiment=catdog_ex

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create visualization report
        python scripts/create_training_report.py

        # Create and post the report
        cml comment create report.md 